baseURL = 'https://kamenlabs.github.io/'
title = 'Kameň Labs'
theme = 'ananke'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[languages]
  [languages.en]
    contentDir = 'content/english'
    languageName = 'English'
    weight = 10
  [languages.ua]
    contentDir = 'content/ukrainian'
    languageName = 'Українська'
    weight = 20